name: inspection_app
description: "Inspection Record Form App with EXIF metadata parsing and PDF export."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: 1.0.7
  geolocator: 10.1.0
  intl: ^0.19.0
  pdf: ^3.10.7
  printing: ^5.11.1
  exif: ^3.1.2
  permission_handler: 11.3.1  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
